# Generated by Django 3.1.3 on 2022-04-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_auto_20220409_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
