name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
           python-version: 3.9
      - name: Install requirements
        run: |
            pip install -r requirements.txt
      - name: Run tests
        run: |
            cd onestopbooks
            coverage run ./manage.py test
            coverage xml
      - name: fix code coverage paths
        run: |
          sed -i 's/\/home\/runner\/work\/CS-4360\/CS-4360\//\/github\/workspace\//g' onestopbooks/coverage.xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
